### ISSUE TITLE
Help running up the WIP ir-textarea

### ISSUE THREAD

**Issue by Analect** [IgorRubinovich/ir-textarea#1]
@IgorRubinovich 
I realise ir-textarea is still a WIP and under development.  It seems like it's a very full-functioned text editor .. the only good polymer example I've been able to find on github and so I was trying to get it up and running, even in its unfinished state, just to get an idea for its capabiltities.  

I think the gulpfile isn't up to date (tried `gulp serve`), so was just using a python `SimpleHTTPServer`, and changed references in the ir-textarea.html to reference the `/bower_components/` folder in the repo. I manually installed a few of the missing bower components, but am still not able to get anything working on either branch.

Perhaps I should just wait a while longer .. otherwise, if you have any pointers for me to get it up and running in it current state, that would be very much appreciated.

Thanks,
Colum

**Comment by IgorRubinovich** [comment]
Hi Colum,
thanks for willing to try it out.
You're right it's under heavy dev (in fact myself and other people are working on it as I type).

The most current version is now under feat/ir-textarea-caret branch updated a few times a day - you need to pull that one.

You've just moved me to advance the demo folder to something that actually works, so to see where it is now simply bower install from the demo directory and then use any http server from there.

Some notes on the demo:
1. Contains some intentionally ugly html and line breaks as this is the base for tests.
2. Installs with ir-gallery (https://github.com/IgorRubinovich/ir-gallery), which besides being Polymer-based slider gallery also demonstrates integration with ir-textarea: clicking on a gallery inside the textarea will show a context menu with a "setup..." option which calls out a setup dialog for the gallery instance that is defined _as part of the gallery_. This is a key feature/advantage that caused the development of the rest of it - to be able to define any custom elements that may be embedded and configured right in the text.

As we're struggling through the contenteditable quirks (and its interaction with custom elements), we have disabled some features like undo/redo, drag/drop for custom elements and a few other niceties. They had been developed and are coming back shortly. I believe it's a matter of less than a month to make it fully functional in Chrome and possibly in Firefox. IE will probably take a bit longer - but then again it may also depend on community support.

Just in case you're willing to contribute - we're very much in a rush and any help would be highly appreciated :)

Thanks,
Igor

**Comment by Analect** [comment]
@IgorRubinovich 
Appreciate the detail. I will try to get this going.
Not sure I'm of much help to you on the coding side, but might be able to assist with some documentation, if that's of any value.

**Comment by IgorRubinovich** [comment]
I'll take your word for it, we will need the docs in just a little while.

**Comment by IgorRubinovich** [comment]
instructions are now available and will be updated at the [wiki](https://github.com/IgorRubinovich/ir-textarea/wiki).

**Comment by Analect** [comment]
@IgorRubinovich 
Thanks. In the Wiki, should the [getting-it](https://github.com/IgorRubinovich/ir-textarea/wiki#getting-it) section reference the [ir-textarea-caret](https://github.com/IgorRubinovich/ir-textarea/tree/feat/ir-textarea-caret) branch rather than **ir-textarea-range** one?

For now, is that [demo](https://github.com/IgorRubinovich/ir-textarea/tree/feat/ir-textarea-caret/demo) folder you created last week still the best place to view a working prototype, since I don't think gulp has been wired up on the **ir-textarea-caret** branch as yet?

**Comment by IgorRubinovich** [comment]
yes demo is still the right place. we're completing some key algorithms and hope to have the main component updated this week.
thanks for noting the branch, I updated the wiki.

**Comment by IgorRubinovich** [comment]
ah yes gulp. you don't need it, ignore the gulpfile.
simply serve the files from demo with anything like simple-server.
